# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='name',
            field=models.CharField(db_index=True, max_length=1100, verbose_name='Alias'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(db_index=True, max_length=1100, verbose_name='Article name'),
        ),
    ]
