# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_auto_20160419_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='name',
            field=models.CharField(db_index=True, max_length=1100, unique=True, verbose_name='Alias'),
        ),
        migrations.AlterField(
            model_name='alias',
            name='slug',
            field=models.SlugField(editable=False, max_length=1100, unique=True, verbose_name='Slug'),
        ),
    ]
