# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_auto_20160518_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='locale',
            field=models.SlugField(default='en', editable=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalarticle',
            name='locale',
            field=models.SlugField(default='en', editable=False, max_length=10),
            preserve_default=False,
        ),
    ]
