language: python
python:
  - 3.4
  - 3.5
  - nightly
services:
  - postgresql
install:
  - "pip install -r requirements.txt"
  - "pip install -r dev-requirements.txt"
env:
  - "INTEGRATION_TEST_DRIVER=phantomjs"
script: "python manage.py test"
